---
# インベントリ
# サーバの ansible_host は各 playbook の冒頭で terraform output から動的に設定される

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

  children:
    servers:
      hosts:
        dis-poc-sv1:
        dis-poc-sv2:
        dis-poc-sv3:
