#!/bin/bash
set -e

WORKSPACE=/workspaces/sakura-talos-argocd

# ---------------------------------------------------------------
# TF_VAR_ 環境変数を ~/.bashrc に転記
# ---------------------------------------------------------------
cat << 'INNER_EOF' >> ~/.bashrc
# Export TF_VAR_ variables from Codespaces secrets
for var in TALOS_VERSION KUBERNETES_VERSION CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_ACCESS_TOKEN SAKURA_ACCESS_TOKEN SAKURA_ACCESS_TOKEN_SECRET SAKURA_LABEL_PREFIX SAKURA_REGION SAKURA_SERVER_CPU SAKURA_SERVER_MEMORY SAKURA_SERVER_COMMITMENT SAKURA_SERVER_CPU_MODEL DOMAIN LE_ENVIRONMENT SAKURA_ISO_IMAGE_ID GH_ORGANIZATION GH_CLIENT_ID_GRAFANA GH_CLIENT_SECRET_GRAFANA GH_CLIENT_ID_ARGOCD GH_CLIENT_SECRET_ARGOCD AUTO_SHUTDOWN_AT_UTC; do
    if [ -n "${!var}" ]; then
        export TF_VAR_$(echo "$var" | tr '[:upper:]' '[:lower:]')="${!var}"
    fi
done
INNER_EOF

# ---------------------------------------------------------------
# ansible-playbook aliases を ~/.bashrc に追加
# playbooks/<name>.yml → alias <name>='ansible-playbook ...'
# ---------------------------------------------------------------
cat << INNER_EOF >> ~/.bashrc

# ansible-playbook aliases (generated by post-create.sh)
# ANSIBLE_CONFIG を明示して world-writable 警告を回避する
for playbook in ${WORKSPACE}/ansible/playbooks/*.yml; do
    alias_name=\$(basename -s .yml "\${playbook}")
    alias "\${alias_name}"="(cd ${WORKSPACE}/ansible && ANSIBLE_CONFIG=${WORKSPACE}/ansible/ansible.cfg ansible-playbook playbooks/\${alias_name}.yml)"
done
INNER_EOF

# ---------------------------------------------------------------
# Ansible Galaxy コレクション
# (ansible-core / jinja2 は devcontainer.json の features で導入済み)
# ---------------------------------------------------------------
ansible-galaxy collection install community.general kubernetes.core ansible.utils 2>/dev/null || true
# Ansible が使用する Python venv に kubernetes/jsonpatch/netaddr をインストール
# (ansible-playbook が使用する Python = ansible --version で確認できるパス)
# netaddr は ansible.utils.ipaddr フィルタ (CIDR → dotted netmask 変換) に必要
ANSIBLE_PYTHON=$(ansible --version 2>/dev/null | awk '/python version/{gsub(/.*\(|\).*/,""); print}')
if [ -n "$ANSIBLE_PYTHON" ] && [ -x "$ANSIBLE_PYTHON" ]; then
    echo "==> Ansible Python (${ANSIBLE_PYTHON}) に kubernetes/jsonpatch/netaddr をインストール中..."
    "$ANSIBLE_PYTHON" -m pip install --quiet kubernetes jsonpatch netaddr 2>/dev/null || true
else
    echo "==> Ansible Python が見つかりませんでした。スキップします。"
fi

# ---------------------------------------------------------------
# talosctl インストール
# ---------------------------------------------------------------
TALOS_VERSION="${TALOS_VERSION:-v1.13.8}"
TALOSCTL_ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
echo "==> talosctl ${TALOS_VERSION} をインストール中..."
curl -sfL "https://github.com/siderolabs/talos/releases/download/${TALOS_VERSION}/talosctl-linux-${TALOSCTL_ARCH}" \
  -o /tmp/talosctl
sudo install -o root -g root -m 0755 /tmp/talosctl /usr/local/bin/talosctl
rm -f /tmp/talosctl
talosctl version --client

# ---------------------------------------------------------------
# crane (go-containerregistry) インストール
# Docker 不要の OCI イメージビルド・push ツール
# ---------------------------------------------------------------
CRANE_VERSION="v0.21.0"
CRANE_ARCH=$(uname -m | sed 's/x86_64/x86_64/;s/aarch64/arm64/')
echo "==> crane ${CRANE_VERSION} をインストール中..."
curl -sfL "https://github.com/google/go-containerregistry/releases/download/${CRANE_VERSION}/go-containerregistry_Linux_${CRANE_ARCH}.tar.gz" \
  | sudo tar -xz -C /usr/local/bin crane
sudo chmod +x /usr/local/bin/crane
crane version

# ---------------------------------------------------------------
# kubectl インストール
# ---------------------------------------------------------------
KUBECTL_VERSION=$(curl -sfL https://dl.k8s.io/release/stable.txt)
KUBECTL_ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
echo "==> kubectl ${KUBECTL_VERSION} をインストール中..."
sudo curl -sfL "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${KUBECTL_ARCH}/kubectl" \
  -o /usr/local/bin/kubectl
sudo chmod +x /usr/local/bin/kubectl
kubectl version --client

# ---------------------------------------------------------------
# helm インストール
# ---------------------------------------------------------------
echo "==> helm をインストール中..."
curl -sfL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
sudo chmod +x /usr/local/bin/helm
helm version

# ---------------------------------------------------------------
# .ssh ディレクトリを作成 (Terraform が秘密鍵を書き込む先)
# ---------------------------------------------------------------
mkdir -p "${WORKSPACE}/.ssh"
chmod 700 "${WORKSPACE}/.ssh"

echo "==> post-create.sh 完了。"
echo "    次のステップ: build-infra または ansible-playbook ansible/playbooks/build-infra.yml"
