#!/bin/bash
set -e

WORKSPACE=/workspaces/sakura-flatcar-k3s-argocd-iac

# ---------------------------------------------------------------
# TF_VAR_ 環境変数を ~/.bashrc に転記
# ---------------------------------------------------------------
cat << 'INNER_EOF' >> ~/.bashrc
# Export TF_VAR_ variables from Codespaces secrets
for var in AWS_ROLE_ARN CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_ACCESS_TOKEN SAKURA_ACCESS_TOKEN SAKURA_ACCESS_TOKEN_SECRET SAKURA_LABEL_PREFIX SAKURA_REGION SAKURA_SERVER_CPU SAKURA_SERVER_MEMORY SAKURA_SERVER_COMMITMENT SAKURA_SERVER_CPU_MODEL DOMAIN LE_ENVIRONMENT SAKURA_ISO_IMAGE_ID GH_ORGANIZATION GH_CLIENT_ID_GRAFANA GH_CLIENT_SECRET_GRAFANA GH_CLIENT_ID_ARGOCD GH_CLIENT_SECRET_ARGOCD AUTO_SHUTDOWN_AT_UTC; do
    if [ -n "${!var}" ]; then
        export TF_VAR_$(echo "$var" | tr '[:upper:]' '[:lower:]')="${!var}"
    fi
done
INNER_EOF

# ---------------------------------------------------------------
# ansible-playbook aliases を ~/.bashrc に追加
# playbooks/<name>.yml → alias <name>='ansible-playbook ...'
# ---------------------------------------------------------------
cat << INNER_EOF >> ~/.bashrc

# ansible-playbook aliases (generated by post-create.sh)
# ANSIBLE_CONFIG を明示して world-writable 警告を回避する
for playbook in ${WORKSPACE}/ansible/playbooks/*.yml; do
    alias_name=\$(basename -s .yml "\${playbook}")
    alias "\${alias_name}"="(cd ${WORKSPACE}/ansible && ANSIBLE_CONFIG=${WORKSPACE}/ansible/ansible.cfg ansible-playbook playbooks/\${alias_name}.yml)"
done
INNER_EOF

# ---------------------------------------------------------------
# Ansible Galaxy コレクション
# (ansible-core / jinja2 は devcontainer.json の features で導入済み)
# ---------------------------------------------------------------
ansible-galaxy collection install community.general kubernetes.core 2>/dev/null || true
# Ansible が使用する Python venv に kubernetes/jsonpatch をインストール
# (ansible-playbook が使用する Python = ansible --version で確認できるパス)
ANSIBLE_PYTHON=$(ansible --version 2>/dev/null | awk '/python version/{gsub(/.*\(|\).*/,""); print}')
if [ -n "$ANSIBLE_PYTHON" ] && [ -x "$ANSIBLE_PYTHON" ]; then
    echo "==> Ansible Python (${ANSIBLE_PYTHON}) に kubernetes/jsonpatch をインストール中..."
    "$ANSIBLE_PYTHON" -m pip install --quiet kubernetes jsonpatch 2>/dev/null || true
else
    echo "==> Ansible Python が見つかりませんでした。スキップします。"
fi

# ---------------------------------------------------------------
# butane インストール
# ---------------------------------------------------------------
BUTANE_VERSION="v0.21.0"
ARCH=$(uname -m)
BUTANE_URL="https://github.com/coreos/butane/releases/download/${BUTANE_VERSION}/butane-${ARCH}-unknown-linux-gnu"
echo "==> butane ${BUTANE_VERSION} をインストール中..."
sudo curl -sfL "${BUTANE_URL}" -o /usr/local/bin/butane
sudo chmod +x /usr/local/bin/butane
butane --version

# ---------------------------------------------------------------
# crane (go-containerregistry) インストール
# Docker 不要の OCI イメージビルド・push ツール
# ---------------------------------------------------------------
CRANE_VERSION="v0.21.0"
CRANE_ARCH=$(uname -m | sed 's/x86_64/x86_64/;s/aarch64/arm64/')
echo "==> crane ${CRANE_VERSION} をインストール中..."
curl -sfL "https://github.com/google/go-containerregistry/releases/download/${CRANE_VERSION}/go-containerregistry_Linux_${CRANE_ARCH}.tar.gz" \
  | sudo tar -xz -C /usr/local/bin crane
sudo chmod +x /usr/local/bin/crane
crane version

# ---------------------------------------------------------------
# kubectl インストール
# ---------------------------------------------------------------
KUBECTL_VERSION=$(curl -sfL https://dl.k8s.io/release/stable.txt)
KUBECTL_ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
echo "==> kubectl ${KUBECTL_VERSION} をインストール中..."
sudo curl -sfL "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${KUBECTL_ARCH}/kubectl" \
  -o /usr/local/bin/kubectl
sudo chmod +x /usr/local/bin/kubectl
kubectl version --client

# ---------------------------------------------------------------
# helm インストール
# ---------------------------------------------------------------
echo "==> helm をインストール中..."
curl -sfL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
sudo chmod +x /usr/local/bin/helm
helm version

# ---------------------------------------------------------------
# AWS Session Manager Plugin インストール
# (aws ssm start-session でポートフォワード等を行うために必要)
# ---------------------------------------------------------------
SSM_ARCH=$(uname -m | sed 's/x86_64/ubuntu_64bit/;s/aarch64/ubuntu_arm64/')
echo "==> session-manager-plugin をインストール中..."
curl -sfL "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/${SSM_ARCH}/session-manager-plugin.deb" \
  -o /tmp/session-manager-plugin.deb
sudo dpkg -i /tmp/session-manager-plugin.deb
rm -f /tmp/session-manager-plugin.deb
session-manager-plugin --version

# ---------------------------------------------------------------
# .ssh ディレクトリを作成 (Terraform が秘密鍵を書き込む先)
# ---------------------------------------------------------------
mkdir -p "${WORKSPACE}/.ssh"
chmod 700 "${WORKSPACE}/.ssh"

echo "==> post-create.sh 完了。"
echo "    次のステップ: build-infra または ansible-playbook ansible/playbooks/build-infra.yml"
